PROGRAM E_572;
VAR F1,F2,F3:FILE OF INTEGER;
    I,N:BYTE;X:INTEGER;
BEGIN
REPEAT
WRITE('N=');READLN(N);
UNTIL(N>2)AND(N<21);
{MKDIR('C:\BP');
MKDIR('C:\BP\FILE1');
MKDIR('C:\BB1');  }
ASSIGN(F1,'C:\BP\FILE1\DD1.DAT');
REWRITE(F1);
FOR I:=1 TO N DO
BEGIN
READ(X);WRITE(F1,X)
END;
CLOSE(F1);
ASSIGN(F3,'D3.DAT');
REWRITE(F3);
RESET(F1);
WHILE NOT EOF(F1) DO
BEGIN
READ(F1,X);WRITE(F3,X)
END;
ASSIGN(F2,'C:\BB1\DD2.DAT');
REWRITE(F2);
REWRITE(F1);
RESET(F3);
WHILE NOT EOF(F3) DO
BEGIN
READ(F3,X);
IF X MOD 2=0
THEN WRITE(F1,X)
ELSE WRITE(F2,X)
END;
CLOSE(F1);CLOSE(F2);CLOSE(F3);
REWRITE(F3);ERASE(F3);
RESET(F1);
WHILE NOT EOF(F1) DO
BEGIN
READ(F1,X);
WRITE('X1=',X)
END;
CLOSE(F1);
RESET(F2);
WHILE NOT EOF(F2) DO
BEGIN
READ(F2,X);
WRITE('X2=',X);
END;
CLOSE(F2) END.
